Repository slid-todo/front, pull requests merged in 2025-01, with the labels that each got.

#176 [Feat] Add aria label in goals page
  src/components/Goals/GoalList/GoalHeader/index.tsx
Labels: ✨ Feature

#185 [Feat] Add google seo meta tag
  src/app/layout.tsx
Labels: 🥰 Accessibility

#190 Feat: 404 페이지 제작
  src/app/not-found.tsx
Labels: ✨ Feature, 🎨 Html&css
